-------------Part – A ---------------
--1. Create a cursor Course_Cursor to fetch all rows from COURSE table and display them. 
DECLARE COURSE_CURSOR CURSOR
FOR
SELECT COURSEID, COURSENAME, COURSECREDITS
FROM COURSE;

DECLARE @CID VARCHAR(10), @CNAME VARCHAR(100), @CREDITS INT;

OPEN COURSE_CURSOR;
FETCH NEXT FROM COURSE_CURSOR INTO @CID, @CNAME, @CREDITS;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @CID + ' - ' + @CNAME + ' - ' + CAST(@CREDITS AS VARCHAR);
    FETCH NEXT FROM COURSE_CURSOR INTO @CID, @CNAME, @CREDITS;
END
 
CLOSE COURSE_CURSOR;
DEALLOCATE COURSE_CURSOR;


--2. Create a cursor Student_Cursor_Fetch to fetch records in form of StudentID_StudentName (Example: 1_Raj Patel). 
DECLARE STUDENT_CURSOR_FETCH CURSOR
FOR
SELECT STUDENTID, STUNAME FROM STUDENT;

DECLARE @SID INT, @SNAME VARCHAR(100);

OPEN STUDENT_CURSOR_FETCH;
FETCH NEXT FROM STUDENT_CURSOR_FETCH INTO @SID, @SNAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT CAST(@SID AS VARCHAR) + '_' + @SNAME;
    FETCH NEXT FROM STUDENT_CURSOR_FETCH INTO @SID, @SNAME;
END

CLOSE STUDENT_CURSOR_FETCH;
DEALLOCATE STUDENT_CURSOR_FETCH;


--3. Create a cursor to find and display all courses with Credits greater than 3. 

GO
DECLARE COURSE_CREDIT_CURSOR CURSOR
FOR
SELECT COURSENAME, COURSECREDITS
FROM COURSE
WHERE COURSECREDITS > 3;

DECLARE @CNAME VARCHAR(100) , @CREDIT INT;

OPEN COURSE_CREDIT_CURSOR;
FETCH NEXT FROM COURSE_CREDIT_CURSOR INTO @CNAME, @CREDIT;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @CNAME + ' - ' + CAST(@CREDIT AS VARCHAR);
    FETCH NEXT FROM COURSE_CREDIT_CURSOR INTO @CNAME, @CREDIT;
END

CLOSE COURSE_CREDIT_CURSOR;
DEALLOCATE COURSE_CREDIT_CURSOR;

--4. Create a cursor to display all students who enrolled in year 2021 or later. 
DECLARE STUDENT_YEAR_CURSOR CURSOR
FOR
SELECT STUNAME
FROM STUDENT
WHERE STUENROLLMENTYEAR >= 2021;

DECLARE @SNAME VARCHAR(100);

OPEN STUDENT_YEAR_CURSOR;
FETCH NEXT FROM STUDENT_YEAR_CURSOR INTO @SNAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @SNAME;
    FETCH NEXT FROM STUDENT_YEAR_CURSOR INTO @SNAME;
END

CLOSE STUDENT_YEAR_CURSOR;
DEALLOCATE STUDENT_YEAR_CURSOR;


--5. Create a cursor Course_CursorUpdate that retrieves all courses and increases Credits by 1 for courses with Credits less than 4. 
GO
DECLARE COURSE_CURSORUPDATE CURSOR
FOR
SELECT COURSEID, COURSECREDITS FROM COURSE;

DECLARE @CID VARCHAR(10), @CREDIT INT;

OPEN COURSE_CURSORUPDATE;
FETCH NEXT FROM COURSE_CURSORUPDATE INTO @CID, @CREDIT;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF @CREDIT < 4
        UPDATE COURSE
        SET COURSECREDITS = COURSECREDITS + 1
        WHERE COURSEID = @CID;

    FETCH NEXT FROM COURSE_CURSORUPDATE INTO @CID, @CREDIT;
END

CLOSE COURSE_CURSORUPDATE;
DEALLOCATE COURSE_CURSORUPDATE;


--6. Create a Cursor to fetch Student Name with Course Name (Example: Raj Patel is enrolled in Database Management System) 
DECLARE STUDENT_COURSE_CURSOR CURSOR
FOR
SELECT S.STUNAME, C.COURSENAME
FROM STUDENT S
JOIN ENROLLMENT E ON S.STUDENTID = E.STUDENTID
JOIN COURSE C ON E.COURSEID = C.COURSEID;

DECLARE @SNAME VARCHAR(100), @CNAME VARCHAR(100);

OPEN STUDENT_COURSE_CURSOR;
FETCH NEXT FROM STUDENT_COURSE_CURSOR INTO @SNAME, @CNAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @SNAME + ' IS ENROLLED IN ' + @CNAME;
    FETCH NEXT FROM STUDENT_COURSE_CURSOR INTO @SNAME, @CNAME;
END

CLOSE STUDENT_COURSE_CURSOR;
DEALLOCATE STUDENT_COURSE_CURSOR;

--7. Create a cursor to insert data into new table if student belong to ‘CSE’ department. (create new table 
--CSEStudent with relevant columns)
CREATE TABLE CSESTUDENT
(
    STUDENTID INT ,
    STUNAME VARCHAR(20),
    STUDEPARTMENT VARCHAR(10)
)

GO
DECLARE CSE_CURSOR CURSOR
FOR
SELECT STUDENTID, STUNAME
FROM STUDENT
WHERE STUDEPARTMENT = 'CSE';

DECLARE @SID INT, @SNAME VARCHAR(100);

OPEN CSE_CURSOR;
FETCH NEXT FROM CSE_CURSOR INTO @SID, @SNAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    INSERT INTO CSESTUDENT VALUES (@SID, @SNAME, 'CSE');
    FETCH NEXT FROM CSE_CURSOR INTO @SID, @SNAME;
END

CLOSE CSE_CURSOR;
DEALLOCATE CSE_CURSOR;

SELECT * FROM CSESTUDENT 

------------Part – B --------------------

--8. Create a cursor to update all NULL grades to 'F' for enrollments with Status 'Completed' 
DECLARE GRADE_CURSOR CURSOR
FOR
SELECT ENROLLMENTID
FROM ENROLLMENT
WHERE GRADE IS NULL
AND ENROLLMENTSTATUS = 'COMPLETED';

DECLARE @EID INT;

OPEN GRADE_CURSOR;
FETCH NEXT FROM GRADE_CURSOR INTO @EID;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE ENROLLMENT
    SET GRADE = 'F'
    WHERE ENROLLMENTID = @EID;

    FETCH NEXT FROM GRADE_CURSOR INTO @EID;
END

CLOSE GRADE_CURSOR;
DEALLOCATE GRADE_CURSOR;

select * from ENROLLMENT


--9. Cursor to show Faculty with Course they teach (EX: Dr. Sheth teaches Data structure) 
     DECLARE @FNAME VARCHAR(100), @CNAME VARCHAR(100)

     DECLARE Faculty_Cursor CURSOR FOR
     SELECT F.FacultyName,C.CourseName FROM
     COURSE_ASSIGNMENT CA JOIN COURSE C
     ON CA.CourseID = C.CourseID
     JOIN FACULTY F
     ON CA.FacultyID = F.FacultyID

     OPEN Faculty_Cursor;

     FETCH NEXT FROM Faculty_Cursor INTO @FNAME,@CNAME;
 
     WHILE @@FETCH_STATUS = 0
     BEGIN
	       PRINT @FNAME + ' teaches ' + @CNAME;

	       FETCH NEXT FROM Faculty_Cursor INTO @FNAME,@CNAME;
     END;

     CLOSE Faculty_Cursor;

     DEALLOCATE Faculty_Cursor;


------------------Part – C ------------------

--10. Cursor to calculate total credits per student (Example: Raj Patel has total credits = 15)
      DECLARE @SID INT,@SNAME VARCHAR(100),@TOTAL INT

      DECLARE Credit_Cursor CURSOR FOR
      SELECT S.StudentID,S.StuName,SUM(C.CourseCredits)
      FROM STUDENT S JOIN ENROLLMENT E
      ON S.StudentID = E.StudentID
      JOIN COURSE C
      ON C.CourseID = E.CourseID
      GROUP BY S.StudentID,S.StuName;

      OPEN Credit_Cursor;

      FETCH NEXT FROM Credit_Cursor INTO @SID,@SNAME,@TOTAL;

      WHILE @@FETCH_STATUS = 0
      BEGIN
	        PRINT @SNAME + ' has total credits = ' + CAST(@TOTAL AS VARCHAR);
	        FETCH NEXT FROM Credit_Cursor INTO @SID,@SNAME,@TOTAL;
      END;

      CLOSE Credit_Cursor;
      DEALLOCATE Credit_Cursor;

