--Table : Log(LogMessage varchar(100), logDate Datetime)
SELECT * FROM LOG
SELECT * FROM STUDENT
SELECT * FROM ENROLLMENT
--Part – A
--1.Create trigger for blocking student deletion.
	GO
	CREATE OR ALTER TRIGGER TRIG_STU_BLOCK_DELETION
	ON STUDENT
	INSTEAD OF DELETE
	AS
	BEGIN
		PRINT 'STUDENT NOT DELETED'	
	END
	DELETE FROM STUDENT WHERE StudentID = 1
	DROP TRIGGER TRIG_STU_BLOCK_DELETION
--2.Create trigger for making course read-only.
	GO
	CREATE OR ALTER TRIGGER TRIG_COURSE_READ
	ON COURSE
	INSTEAD OF INSERT,UPDATE,DELETE
	AS
	BEGIN
		PRINT 'COURSE IS READ ONLY'
	END
	DROP TRIGGER TRIG_COURSE_READ
--3.Create trigger for preventing faculty removal.
	GO
	CREATE OR ALTER TRIGGER TRIG_FACULTY_REMOVE
	ON FACULTY
	INSTEAD OF DELETE
	AS
	BEGIN
		PRINT 'FACULTY NOT DELETED'
	END
	DELETE FROM FACULTY WHERE FacultyID = 101
	DROP TRIGGER TRIG_FACULTY_REMOVE
--4.Create instead of trigger to log all operations on COURSE (INSERT/UPDATE/DELETE) into Log table. (Example: INSERT/UPDATE/DELETE operations are blocked for you in course table)
	GO
	CREATE OR ALTER TRIGGER TRIG_COURSE_OPERATION
	ON COURSE
	INSTEAD OF INSERT,UPDATE,DELETE
	AS
	BEGIN
		INSERT INTO LOG VALUES ('OPERATION BLOCKED ON COURSE',GETDATE())
		PRINT 'INSERT/UPDATE/DELETE NOT ALLOWED'
	END
	DELETE COURSE WHERE CourseID = 'CS101'
	DROP TRIGGER TRIG_COURSE_OPERATION
--5.Create trigger to Block student to update their enrollment year and print message ‘students are not allowed to update their enrollment year’
	GO
	CREATE OR ALTER TRIGGER TRIG_STU_ENROLLMENT
	ON STUDENT
	INSTEAD OF UPDATE
	AS
	BEGIN
		IF UPDATE(StuEnrollmentYear)
			PRINT 'STUDENT ARE NOT ALLOWED TO UPDATE'
		ELSE
			INSERT INTO STUDENT SELECT * FROM inserted
	END
	DROP TRIGGER TRIG_STU_ENROLLMENT
--6.Create trigger for student age validation (Min 18).
	GO
	CREATE OR ALTER TRIGGER TRIG_STUDENT_AGE
	ON STUDENT
	INSTEAD OF INSERT
	AS
	BEGIN
		IF EXISTS (SELECT * FROM inserted WHERE DATEDIFF(YEAR,GETDATE(),'StuDateOfBirth')<18)
			PRINT 'STUDENT AGE MUST BE GREATER THAN 18'
		ELSE 
			INSERT INTO STUDENT SELECT * FROM inserted
	END
	INSERT INTO STUDENT VALUES (12,'RONIT','ronit@univ.edu',8783922398,'CSE','2006-09-23',2024,NULL)
	DROP TRIGGER TRIG_STUDENT_AGE

--Part – B
--7.Create trigger for unique faculty’s email check.
	GO
	CREATE OR ALTER TRIGGER TRIG_FACULTY_EMAIL
	ON FACULTY
	INSTEAD OF INSERT
	AS
	BEGIN
		IF EXISTS (
			SELECT 1 FROM FACULTY JOIN inserted ON FACULTY.FacultyEmail = inserted.FacultyEmail
		)
		BEGIN
			PRINT 'FACULTY EMAIL MUST BE UNIQUE.'
			RETURN
		END
		INSERT INTO FACULTY SELECT * FROM inserted
	END
--8.Create trigger for preventing duplicate enrollment.
	GO
	CREATE OR ALTER TRIGGER TRIG_DUPLICATE_ENROLLMENT
	ON ENROLLMENT
	INSTEAD OF INSERT
	AS
	BEGIN
		IF EXISTS (
			SELECT 1 FROM ENROLLMENT JOIN inserted ON ENROLLMENT.StudentID = inserted.StudentID
			AND ENROLLMENT.CourseID = inserted.CourseID
		)
		BEGIN
			PRINT 'DUPLICATE ENROLLMENT IS NOT ALLOWED'
			RETURN
		END
		INSERT INTO ENROLLMENT SELECT * FROM inserted
	END
--Part - C

--9.Create trigger to Allow enrolment in month from Jan to August, otherwise print message enrolment closed.
	GO
    CREATE OR ALTER TRIGGER TRIG_ENROLLMENT_CHECK
	ON ENROLLMENT
	INSTEAD OF INSERT
	AS
	BEGIN
		DECLARE @MONTH INT = MONTH(GETDATE())
		IF @MONTH NOT BETWEEN 1 AND 8
		BEGIN
			PRINT 'ENROOLMENT CLOSED'
			RETURN
		END
		INSERT INTO ENROLLMENT
		SELECT * FROM ENROLLMENT
	END
--10.Create trigger to Allow only grade change in enrollment (block other updates)
	GO
	CREATE OR ALTER TRIGGER TRIG_ENROLLMENT_CHANGE
	ON ENROLLMENT
	INSTEAD OF UPDATE
	AS
	BEGIN
		IF UPDATE(StudentID) OR UPDATE(CourseID) OR UPDATE(EnrollmentDate)
		BEGIN
			PRINT 'ONLY GRADE CHANGE IS ALLOWED.'
			RETURN
		END
		UPDATE ENROLLMENT
		SET Grade = inserted.Grade
		FROM ENROLLMENT
		INNER JOIN inserted ON ENROLLMENT.EnrollmentID = inserted.EnrollmentID
	END